{% set name = "mafredo" %}
{% set version = "2025.4.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  url: https://files.pythonhosted.org/packages/ab/3a/f37f5e36a64727a05c78b8f243967cd8bef27ab888225d57c7b6493c8b4b/mafredo-{{ version }}.tar.gz # hard-copied
  sha256: b1c4d07bde57f71690e8e70264ae767423ca452d22269140944f2be055684652

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.5
    - pyscaffold
    - setuptools
  run:
    - python >=3.5
    - xarray
    - scipy
    - numpy
    - pyyaml
    - matplotlib

test:
  imports:
    - mafredo

about:
  home: https://github.com/RubendeBruin/mafredo
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: "Marine Frequency Domain"
  doc_url: https://mafredo.readthedocs.io/en/latest/
  dev_url: https://github.com/RubendeBruin/mafredo

extra:
  recipe-maintainers:
    - rubendebruin
