{% set name = "mafredo" %}
{% set version = "2025.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  # url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  url: https://files.pythonhosted.org/packages/58/8c/1731b0f4be8c1444b1f6f7f6c820d765d0f2dfd74adec93e91191cd233f6/mafredo-{{ version }}.tar.gz # hard-copied
  sha256: 402aea055ed2a4ca94433aa13bbf6e5760f9ba406387762a2946ac11642f3c27

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.5
    - pyscaffold
    - setuptools
  run:
    - python >=3.5
    - xarray
    - scipy
    - numpy
    - pyyaml
    - matplotlib

test:
  imports:
    - mafredo

about:
  home: https://github.com/RubendeBruin/mafredo
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: "Marine Frequency Domain"
  doc_url: https://mafredo.readthedocs.io/en/latest/
  dev_url: https://github.com/RubendeBruin/mafredo

extra:
  recipe-maintainers:
    - rubendebruin
